// SPDX-License-Identifier: Apache-2.0

// DO NOT EDIT.
//
// This file has been generated by the Kotlin project in the `generator`
// directory from a Vulkan API registry.

use std::os::raw::c_char;

use crate::MAX_EXTENSION_NAME_SIZE;

/// A Vulkan extension name.
pub type ExtensionName = [c_char; MAX_EXTENSION_NAME_SIZE];

/// `AMD` extensions.
pub mod amd {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_buffer_marker.html>
    pub const BUFFER_MARKER: ExtensionName = name(b"VK_AMD_buffer_marker");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_device_coherent_memory.html>
    pub const DEVICE_COHERENT_MEMORY: ExtensionName = name(b"VK_AMD_device_coherent_memory");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_display_native_hdr.html>
    pub const DISPLAY_NATIVE_HDR: ExtensionName = name(b"VK_AMD_display_native_hdr");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_draw_indirect_count.html>
    pub const DRAW_INDIRECT_COUNT: ExtensionName = name(b"VK_AMD_draw_indirect_count");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_gcn_shader.html>
    pub const GCN_SHADER: ExtensionName = name(b"VK_AMD_gcn_shader");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_gpu_shader_half_float.html>
    #[deprecated(note = "deprecated in favor of `VK_KHR_shader_float16_int8`")]
    pub const GPU_SHADER_HALF_FLOAT: ExtensionName = name(b"VK_AMD_gpu_shader_half_float");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_gpu_shader_int16.html>
    #[deprecated(note = "deprecated in favor of `VK_KHR_shader_float16_int8`")]
    pub const GPU_SHADER_INT16: ExtensionName = name(b"VK_AMD_gpu_shader_int16");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_memory_overallocation_behavior.html>
    pub const MEMORY_OVERALLOCATION_BEHAVIOR: ExtensionName =
        name(b"VK_AMD_memory_overallocation_behavior");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_mixed_attachment_samples.html>
    pub const MIXED_ATTACHMENT_SAMPLES: ExtensionName = name(b"VK_AMD_mixed_attachment_samples");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_negative_viewport_height.html>
    pub const NEGATIVE_VIEWPORT_HEIGHT: ExtensionName = name(b"VK_AMD_negative_viewport_height");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_pipeline_compiler_control.html>
    pub const PIPELINE_COMPILER_CONTROL: ExtensionName = name(b"VK_AMD_pipeline_compiler_control");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_rasterization_order.html>
    pub const RASTERIZATION_ORDER: ExtensionName = name(b"VK_AMD_rasterization_order");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_shader_ballot.html>
    pub const SHADER_BALLOT: ExtensionName = name(b"VK_AMD_shader_ballot");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_shader_core_properties.html>
    pub const SHADER_CORE_PROPERTIES: ExtensionName = name(b"VK_AMD_shader_core_properties");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_shader_core_properties2.html>
    pub const SHADER_CORE_PROPERTIES2: ExtensionName = name(b"VK_AMD_shader_core_properties2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_shader_explicit_vertex_parameter.html>
    pub const SHADER_EXPLICIT_VERTEX_PARAMETER: ExtensionName =
        name(b"VK_AMD_shader_explicit_vertex_parameter");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_shader_fragment_mask.html>
    pub const SHADER_FRAGMENT_MASK: ExtensionName = name(b"VK_AMD_shader_fragment_mask");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_shader_image_load_store_lod.html>
    pub const SHADER_IMAGE_LOAD_STORE_LOD: ExtensionName =
        name(b"VK_AMD_shader_image_load_store_lod");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_shader_info.html>
    pub const SHADER_INFO: ExtensionName = name(b"VK_AMD_shader_info");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_shader_trinary_minmax.html>
    pub const SHADER_TRINARY_MINMAX: ExtensionName = name(b"VK_AMD_shader_trinary_minmax");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_AMD_texture_gather_bias_lod.html>
    pub const TEXTURE_GATHER_BIAS_LOD: ExtensionName = name(b"VK_AMD_texture_gather_bias_lod");
}

/// `ANDROID` extensions.
pub mod android {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_ANDROID_external_memory_android_hardware_buffer.html>
    pub const EXTERNAL_MEMORY_ANDROID_HARDWARE_BUFFER: ExtensionName =
        name(b"VK_ANDROID_external_memory_android_hardware_buffer");
}

/// `EXT` extensions.
pub mod ext {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_4444_formats.html>
    pub const _4444_FORMATS: ExtensionName = name(b"VK_EXT_4444_formats");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_acquire_xlib_display.html>
    pub const ACQUIRE_XLIB_DISPLAY: ExtensionName = name(b"VK_EXT_acquire_xlib_display");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_astc_decode_mode.html>
    pub const ASTC_DECODE_MODE: ExtensionName = name(b"VK_EXT_astc_decode_mode");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_blend_operation_advanced.html>
    pub const BLEND_OPERATION_ADVANCED: ExtensionName = name(b"VK_EXT_blend_operation_advanced");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_buffer_device_address.html>
    #[deprecated(note = "deprecated in favor of `VK_KHR_buffer_device_address`")]
    pub const BUFFER_DEVICE_ADDRESS: ExtensionName = name(b"VK_EXT_buffer_device_address");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_calibrated_timestamps.html>
    pub const CALIBRATED_TIMESTAMPS: ExtensionName = name(b"VK_EXT_calibrated_timestamps");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_conditional_rendering.html>
    pub const CONDITIONAL_RENDERING: ExtensionName = name(b"VK_EXT_conditional_rendering");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_conservative_rasterization.html>
    pub const CONSERVATIVE_RASTERIZATION: ExtensionName =
        name(b"VK_EXT_conservative_rasterization");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_custom_border_color.html>
    pub const CUSTOM_BORDER_COLOR: ExtensionName = name(b"VK_EXT_custom_border_color");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_debug_marker.html>
    pub const DEBUG_MARKER: ExtensionName = name(b"VK_EXT_debug_marker");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_debug_report.html>
    #[deprecated(note = "deprecated in favor of `VK_EXT_debug_utils`")]
    pub const DEBUG_REPORT: ExtensionName = name(b"VK_EXT_debug_report");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_debug_utils.html>
    pub const DEBUG_UTILS: ExtensionName = name(b"VK_EXT_debug_utils");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_depth_clip_enable.html>
    pub const DEPTH_CLIP_ENABLE: ExtensionName = name(b"VK_EXT_depth_clip_enable");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_depth_range_unrestricted.html>
    pub const DEPTH_RANGE_UNRESTRICTED: ExtensionName = name(b"VK_EXT_depth_range_unrestricted");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_descriptor_indexing.html>
    pub const DESCRIPTOR_INDEXING: ExtensionName = name(b"VK_EXT_descriptor_indexing");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_device_memory_report.html>
    pub const DEVICE_MEMORY_REPORT: ExtensionName = name(b"VK_EXT_device_memory_report");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_directfb_surface.html>
    pub const DIRECTFB_SURFACE: ExtensionName = name(b"VK_EXT_directfb_surface");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_direct_mode_display.html>
    pub const DIRECT_MODE_DISPLAY: ExtensionName = name(b"VK_EXT_direct_mode_display");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_discard_rectangles.html>
    pub const DISCARD_RECTANGLES: ExtensionName = name(b"VK_EXT_discard_rectangles");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_display_control.html>
    pub const DISPLAY_CONTROL: ExtensionName = name(b"VK_EXT_display_control");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_display_surface_counter.html>
    pub const DISPLAY_SURFACE_COUNTER: ExtensionName = name(b"VK_EXT_display_surface_counter");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_extended_dynamic_state.html>
    pub const EXTENDED_DYNAMIC_STATE: ExtensionName = name(b"VK_EXT_extended_dynamic_state");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_external_memory_dma_buf.html>
    pub const EXTERNAL_MEMORY_DMA_BUF: ExtensionName = name(b"VK_EXT_external_memory_dma_buf");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_external_memory_host.html>
    pub const EXTERNAL_MEMORY_HOST: ExtensionName = name(b"VK_EXT_external_memory_host");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_filter_cubic.html>
    pub const FILTER_CUBIC: ExtensionName = name(b"VK_EXT_filter_cubic");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_fragment_density_map.html>
    pub const FRAGMENT_DENSITY_MAP: ExtensionName = name(b"VK_EXT_fragment_density_map");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_fragment_density_map2.html>
    pub const FRAGMENT_DENSITY_MAP2: ExtensionName = name(b"VK_EXT_fragment_density_map2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_fragment_shader_interlock.html>
    pub const FRAGMENT_SHADER_INTERLOCK: ExtensionName = name(b"VK_EXT_fragment_shader_interlock");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_full_screen_exclusive.html>
    pub const FULL_SCREEN_EXCLUSIVE: ExtensionName = name(b"VK_EXT_full_screen_exclusive");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_global_priority.html>
    pub const GLOBAL_PRIORITY: ExtensionName = name(b"VK_EXT_global_priority");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_hdr_metadata.html>
    pub const HDR_METADATA: ExtensionName = name(b"VK_EXT_hdr_metadata");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_headless_surface.html>
    pub const HEADLESS_SURFACE: ExtensionName = name(b"VK_EXT_headless_surface");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_host_query_reset.html>
    pub const HOST_QUERY_RESET: ExtensionName = name(b"VK_EXT_host_query_reset");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_image_drm_format_modifier.html>
    pub const IMAGE_DRM_FORMAT_MODIFIER: ExtensionName = name(b"VK_EXT_image_drm_format_modifier");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_image_robustness.html>
    pub const IMAGE_ROBUSTNESS: ExtensionName = name(b"VK_EXT_image_robustness");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_index_type_uint8.html>
    pub const INDEX_TYPE_UINT8: ExtensionName = name(b"VK_EXT_index_type_uint8");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_inline_uniform_block.html>
    pub const INLINE_UNIFORM_BLOCK: ExtensionName = name(b"VK_EXT_inline_uniform_block");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_line_rasterization.html>
    pub const LINE_RASTERIZATION: ExtensionName = name(b"VK_EXT_line_rasterization");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_memory_budget.html>
    pub const MEMORY_BUDGET: ExtensionName = name(b"VK_EXT_memory_budget");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_memory_priority.html>
    pub const MEMORY_PRIORITY: ExtensionName = name(b"VK_EXT_memory_priority");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_metal_surface.html>
    pub const METAL_SURFACE: ExtensionName = name(b"VK_EXT_metal_surface");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_pci_bus_info.html>
    pub const PCI_BUS_INFO: ExtensionName = name(b"VK_EXT_pci_bus_info");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_pipeline_creation_cache_control.html>
    pub const PIPELINE_CREATION_CACHE_CONTROL: ExtensionName =
        name(b"VK_EXT_pipeline_creation_cache_control");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_pipeline_creation_feedback.html>
    pub const PIPELINE_CREATION_FEEDBACK: ExtensionName =
        name(b"VK_EXT_pipeline_creation_feedback");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_post_depth_coverage.html>
    pub const POST_DEPTH_COVERAGE: ExtensionName = name(b"VK_EXT_post_depth_coverage");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_private_data.html>
    pub const PRIVATE_DATA: ExtensionName = name(b"VK_EXT_private_data");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_queue_family_foreign.html>
    pub const QUEUE_FAMILY_FOREIGN: ExtensionName = name(b"VK_EXT_queue_family_foreign");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_robustness2.html>
    pub const ROBUSTNESS2: ExtensionName = name(b"VK_EXT_robustness2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_sampler_filter_minmax.html>
    pub const SAMPLER_FILTER_MINMAX: ExtensionName = name(b"VK_EXT_sampler_filter_minmax");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_sample_locations.html>
    pub const SAMPLE_LOCATIONS: ExtensionName = name(b"VK_EXT_sample_locations");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_scalar_block_layout.html>
    pub const SCALAR_BLOCK_LAYOUT: ExtensionName = name(b"VK_EXT_scalar_block_layout");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_separate_stencil_usage.html>
    pub const SEPARATE_STENCIL_USAGE: ExtensionName = name(b"VK_EXT_separate_stencil_usage");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_shader_atomic_float.html>
    pub const SHADER_ATOMIC_FLOAT: ExtensionName = name(b"VK_EXT_shader_atomic_float");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_shader_demote_to_helper_invocation.html>
    pub const SHADER_DEMOTE_TO_HELPER_INVOCATION: ExtensionName =
        name(b"VK_EXT_shader_demote_to_helper_invocation");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_shader_image_atomic_int64.html>
    pub const SHADER_IMAGE_ATOMIC_INT64: ExtensionName = name(b"VK_EXT_shader_image_atomic_int64");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_shader_stencil_export.html>
    pub const SHADER_STENCIL_EXPORT: ExtensionName = name(b"VK_EXT_shader_stencil_export");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_shader_subgroup_ballot.html>
    #[deprecated(note = "deprecated in favor of `VK_VERSION_1_2`")]
    pub const SHADER_SUBGROUP_BALLOT: ExtensionName = name(b"VK_EXT_shader_subgroup_ballot");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_shader_subgroup_vote.html>
    #[deprecated(note = "deprecated in favor of `VK_VERSION_1_1`")]
    pub const SHADER_SUBGROUP_VOTE: ExtensionName = name(b"VK_EXT_shader_subgroup_vote");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_shader_viewport_index_layer.html>
    pub const SHADER_VIEWPORT_INDEX_LAYER: ExtensionName =
        name(b"VK_EXT_shader_viewport_index_layer");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_subgroup_size_control.html>
    pub const SUBGROUP_SIZE_CONTROL: ExtensionName = name(b"VK_EXT_subgroup_size_control");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_swapchain_colorspace.html>
    pub const SWAPCHAIN_COLORSPACE: ExtensionName = name(b"VK_EXT_swapchain_colorspace");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_texel_buffer_alignment.html>
    pub const TEXEL_BUFFER_ALIGNMENT: ExtensionName = name(b"VK_EXT_texel_buffer_alignment");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_texture_compression_astc_hdr.html>
    pub const TEXTURE_COMPRESSION_ASTC_HDR: ExtensionName =
        name(b"VK_EXT_texture_compression_astc_hdr");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_tooling_info.html>
    pub const TOOLING_INFO: ExtensionName = name(b"VK_EXT_tooling_info");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_transform_feedback.html>
    pub const TRANSFORM_FEEDBACK: ExtensionName = name(b"VK_EXT_transform_feedback");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_validation_cache.html>
    pub const VALIDATION_CACHE: ExtensionName = name(b"VK_EXT_validation_cache");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_validation_features.html>
    pub const VALIDATION_FEATURES: ExtensionName = name(b"VK_EXT_validation_features");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_validation_flags.html>
    #[deprecated(note = "deprecated in favor of `VK_EXT_validation_features`")]
    pub const VALIDATION_FLAGS: ExtensionName = name(b"VK_EXT_validation_flags");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_vertex_attribute_divisor.html>
    pub const VERTEX_ATTRIBUTE_DIVISOR: ExtensionName = name(b"VK_EXT_vertex_attribute_divisor");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_ycbcr_image_arrays.html>
    pub const YCBCR_IMAGE_ARRAYS: ExtensionName = name(b"VK_EXT_ycbcr_image_arrays");
}

/// `FUCHSIA` extensions.
pub mod fuchsia {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_FUCHSIA_imagepipe_surface.html>
    pub const IMAGEPIPE_SURFACE: ExtensionName = name(b"VK_FUCHSIA_imagepipe_surface");
}

/// `GGP` extensions.
pub mod ggp {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_GGP_frame_token.html>
    pub const FRAME_TOKEN: ExtensionName = name(b"VK_GGP_frame_token");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_GGP_stream_descriptor_surface.html>
    pub const STREAM_DESCRIPTOR_SURFACE: ExtensionName = name(b"VK_GGP_stream_descriptor_surface");
}

/// `GOOGLE` extensions.
pub mod google {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_GOOGLE_decorate_string.html>
    pub const DECORATE_STRING: ExtensionName = name(b"VK_GOOGLE_decorate_string");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_GOOGLE_display_timing.html>
    pub const DISPLAY_TIMING: ExtensionName = name(b"VK_GOOGLE_display_timing");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_GOOGLE_hlsl_functionality1.html>
    pub const HLSL_FUNCTIONALITY1: ExtensionName = name(b"VK_GOOGLE_hlsl_functionality1");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_GOOGLE_user_type.html>
    pub const USER_TYPE: ExtensionName = name(b"VK_GOOGLE_user_type");
}

/// `IMG` extensions.
pub mod img {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_IMG_filter_cubic.html>
    pub const FILTER_CUBIC: ExtensionName = name(b"VK_IMG_filter_cubic");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_IMG_format_pvrtc.html>
    pub const FORMAT_PVRTC: ExtensionName = name(b"VK_IMG_format_pvrtc");
}

/// `INTEL` extensions.
pub mod intel {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_INTEL_performance_query.html>
    pub const PERFORMANCE_QUERY: ExtensionName = name(b"VK_INTEL_performance_query");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_INTEL_shader_integer_functions2.html>
    pub const SHADER_INTEGER_FUNCTIONS2: ExtensionName =
        name(b"VK_INTEL_shader_integer_functions2");
}

/// `KHR` extensions.
pub mod khr {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_16bit_storage.html>
    pub const _16BIT_STORAGE: ExtensionName = name(b"VK_KHR_16bit_storage");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_8bit_storage.html>
    pub const _8BIT_STORAGE: ExtensionName = name(b"VK_KHR_8bit_storage");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_android_surface.html>
    pub const ANDROID_SURFACE: ExtensionName = name(b"VK_KHR_android_surface");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_bind_memory2.html>
    pub const BIND_MEMORY2: ExtensionName = name(b"VK_KHR_bind_memory2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_buffer_device_address.html>
    pub const BUFFER_DEVICE_ADDRESS: ExtensionName = name(b"VK_KHR_buffer_device_address");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_copy_commands2.html>
    pub const COPY_COMMANDS2: ExtensionName = name(b"VK_KHR_copy_commands2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_create_renderpass2.html>
    pub const CREATE_RENDERPASS2: ExtensionName = name(b"VK_KHR_create_renderpass2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_dedicated_allocation.html>
    pub const DEDICATED_ALLOCATION: ExtensionName = name(b"VK_KHR_dedicated_allocation");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_deferred_host_operations.html>
    pub const DEFERRED_HOST_OPERATIONS: ExtensionName = name(b"VK_KHR_deferred_host_operations");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_depth_stencil_resolve.html>
    pub const DEPTH_STENCIL_RESOLVE: ExtensionName = name(b"VK_KHR_depth_stencil_resolve");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_descriptor_update_template.html>
    pub const DESCRIPTOR_UPDATE_TEMPLATE: ExtensionName =
        name(b"VK_KHR_descriptor_update_template");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_device_group.html>
    pub const DEVICE_GROUP: ExtensionName = name(b"VK_KHR_device_group");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_device_group_creation.html>
    pub const DEVICE_GROUP_CREATION: ExtensionName = name(b"VK_KHR_device_group_creation");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_display.html>
    pub const DISPLAY: ExtensionName = name(b"VK_KHR_display");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_display_swapchain.html>
    pub const DISPLAY_SWAPCHAIN: ExtensionName = name(b"VK_KHR_display_swapchain");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_draw_indirect_count.html>
    pub const DRAW_INDIRECT_COUNT: ExtensionName = name(b"VK_KHR_draw_indirect_count");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_driver_properties.html>
    pub const DRIVER_PROPERTIES: ExtensionName = name(b"VK_KHR_driver_properties");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_fence.html>
    pub const EXTERNAL_FENCE: ExtensionName = name(b"VK_KHR_external_fence");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_fence_capabilities.html>
    pub const EXTERNAL_FENCE_CAPABILITIES: ExtensionName =
        name(b"VK_KHR_external_fence_capabilities");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_fence_fd.html>
    pub const EXTERNAL_FENCE_FD: ExtensionName = name(b"VK_KHR_external_fence_fd");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_fence_win32.html>
    pub const EXTERNAL_FENCE_WIN32: ExtensionName = name(b"VK_KHR_external_fence_win32");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_memory.html>
    pub const EXTERNAL_MEMORY: ExtensionName = name(b"VK_KHR_external_memory");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_memory_capabilities.html>
    pub const EXTERNAL_MEMORY_CAPABILITIES: ExtensionName =
        name(b"VK_KHR_external_memory_capabilities");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_memory_fd.html>
    pub const EXTERNAL_MEMORY_FD: ExtensionName = name(b"VK_KHR_external_memory_fd");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_memory_win32.html>
    pub const EXTERNAL_MEMORY_WIN32: ExtensionName = name(b"VK_KHR_external_memory_win32");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_semaphore.html>
    pub const EXTERNAL_SEMAPHORE: ExtensionName = name(b"VK_KHR_external_semaphore");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_semaphore_capabilities.html>
    pub const EXTERNAL_SEMAPHORE_CAPABILITIES: ExtensionName =
        name(b"VK_KHR_external_semaphore_capabilities");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_semaphore_fd.html>
    pub const EXTERNAL_SEMAPHORE_FD: ExtensionName = name(b"VK_KHR_external_semaphore_fd");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_semaphore_win32.html>
    pub const EXTERNAL_SEMAPHORE_WIN32: ExtensionName = name(b"VK_KHR_external_semaphore_win32");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_get_display_properties2.html>
    pub const GET_DISPLAY_PROPERTIES2: ExtensionName = name(b"VK_KHR_get_display_properties2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_get_memory_requirements2.html>
    pub const GET_MEMORY_REQUIREMENTS2: ExtensionName = name(b"VK_KHR_get_memory_requirements2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_get_physical_device_properties2.html>
    pub const GET_PHYSICAL_DEVICE_PROPERTIES2: ExtensionName =
        name(b"VK_KHR_get_physical_device_properties2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_get_surface_capabilities2.html>
    pub const GET_SURFACE_CAPABILITIES2: ExtensionName = name(b"VK_KHR_get_surface_capabilities2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_imageless_framebuffer.html>
    pub const IMAGELESS_FRAMEBUFFER: ExtensionName = name(b"VK_KHR_imageless_framebuffer");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_image_format_list.html>
    pub const IMAGE_FORMAT_LIST: ExtensionName = name(b"VK_KHR_image_format_list");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_incremental_present.html>
    pub const INCREMENTAL_PRESENT: ExtensionName = name(b"VK_KHR_incremental_present");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_maintenance1.html>
    pub const MAINTENANCE1: ExtensionName = name(b"VK_KHR_maintenance1");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_maintenance2.html>
    pub const MAINTENANCE2: ExtensionName = name(b"VK_KHR_maintenance2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_maintenance3.html>
    pub const MAINTENANCE3: ExtensionName = name(b"VK_KHR_maintenance3");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_multiview.html>
    pub const MULTIVIEW: ExtensionName = name(b"VK_KHR_multiview");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_performance_query.html>
    pub const PERFORMANCE_QUERY: ExtensionName = name(b"VK_KHR_performance_query");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_pipeline_executable_properties.html>
    pub const PIPELINE_EXECUTABLE_PROPERTIES: ExtensionName =
        name(b"VK_KHR_pipeline_executable_properties");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_pipeline_library.html>
    pub const PIPELINE_LIBRARY: ExtensionName = name(b"VK_KHR_pipeline_library");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_portability_subset.html>
    pub const PORTABILITY_SUBSET: ExtensionName = name(b"VK_KHR_portability_subset");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_push_descriptor.html>
    pub const PUSH_DESCRIPTOR: ExtensionName = name(b"VK_KHR_push_descriptor");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_ray_tracing.html>
    pub const RAY_TRACING: ExtensionName = name(b"VK_KHR_ray_tracing");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_relaxed_block_layout.html>
    pub const RELAXED_BLOCK_LAYOUT: ExtensionName = name(b"VK_KHR_relaxed_block_layout");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_sampler_mirror_clamp_to_edge.html>
    pub const SAMPLER_MIRROR_CLAMP_TO_EDGE: ExtensionName =
        name(b"VK_KHR_sampler_mirror_clamp_to_edge");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_sampler_ycbcr_conversion.html>
    pub const SAMPLER_YCBCR_CONVERSION: ExtensionName = name(b"VK_KHR_sampler_ycbcr_conversion");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_separate_depth_stencil_layouts.html>
    pub const SEPARATE_DEPTH_STENCIL_LAYOUTS: ExtensionName =
        name(b"VK_KHR_separate_depth_stencil_layouts");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_atomic_int64.html>
    pub const SHADER_ATOMIC_INT64: ExtensionName = name(b"VK_KHR_shader_atomic_int64");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_clock.html>
    pub const SHADER_CLOCK: ExtensionName = name(b"VK_KHR_shader_clock");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_draw_parameters.html>
    pub const SHADER_DRAW_PARAMETERS: ExtensionName = name(b"VK_KHR_shader_draw_parameters");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_float16_int8.html>
    pub const SHADER_FLOAT16_INT8: ExtensionName = name(b"VK_KHR_shader_float16_int8");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_float_controls.html>
    pub const SHADER_FLOAT_CONTROLS: ExtensionName = name(b"VK_KHR_shader_float_controls");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_non_semantic_info.html>
    pub const SHADER_NON_SEMANTIC_INFO: ExtensionName = name(b"VK_KHR_shader_non_semantic_info");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shader_subgroup_extended_types.html>
    pub const SHADER_SUBGROUP_EXTENDED_TYPES: ExtensionName =
        name(b"VK_KHR_shader_subgroup_extended_types");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_shared_presentable_image.html>
    pub const SHARED_PRESENTABLE_IMAGE: ExtensionName = name(b"VK_KHR_shared_presentable_image");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_spirv_1_4.html>
    pub const SPIRV_1_4: ExtensionName = name(b"VK_KHR_spirv_1_4");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_storage_buffer_storage_class.html>
    pub const STORAGE_BUFFER_STORAGE_CLASS: ExtensionName =
        name(b"VK_KHR_storage_buffer_storage_class");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_surface.html>
    pub const SURFACE: ExtensionName = name(b"VK_KHR_surface");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_surface_protected_capabilities.html>
    pub const SURFACE_PROTECTED_CAPABILITIES: ExtensionName =
        name(b"VK_KHR_surface_protected_capabilities");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_swapchain.html>
    pub const SWAPCHAIN: ExtensionName = name(b"VK_KHR_swapchain");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_swapchain_mutable_format.html>
    pub const SWAPCHAIN_MUTABLE_FORMAT: ExtensionName = name(b"VK_KHR_swapchain_mutable_format");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_timeline_semaphore.html>
    pub const TIMELINE_SEMAPHORE: ExtensionName = name(b"VK_KHR_timeline_semaphore");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_uniform_buffer_standard_layout.html>
    pub const UNIFORM_BUFFER_STANDARD_LAYOUT: ExtensionName =
        name(b"VK_KHR_uniform_buffer_standard_layout");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_variable_pointers.html>
    pub const VARIABLE_POINTERS: ExtensionName = name(b"VK_KHR_variable_pointers");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_vulkan_memory_model.html>
    pub const VULKAN_MEMORY_MODEL: ExtensionName = name(b"VK_KHR_vulkan_memory_model");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_wayland_surface.html>
    pub const WAYLAND_SURFACE: ExtensionName = name(b"VK_KHR_wayland_surface");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_win32_keyed_mutex.html>
    pub const WIN32_KEYED_MUTEX: ExtensionName = name(b"VK_KHR_win32_keyed_mutex");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_win32_surface.html>
    pub const WIN32_SURFACE: ExtensionName = name(b"VK_KHR_win32_surface");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_xcb_surface.html>
    pub const XCB_SURFACE: ExtensionName = name(b"VK_KHR_xcb_surface");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_xlib_surface.html>
    pub const XLIB_SURFACE: ExtensionName = name(b"VK_KHR_xlib_surface");
}

/// `MVK` extensions.
pub mod mvk {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_MVK_ios_surface.html>
    #[deprecated(note = "deprecated in favor of `VK_EXT_metal_surface`")]
    pub const IOS_SURFACE: ExtensionName = name(b"VK_MVK_ios_surface");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_MVK_macos_surface.html>
    #[deprecated(note = "deprecated in favor of `VK_EXT_metal_surface`")]
    pub const MACOS_SURFACE: ExtensionName = name(b"VK_MVK_macos_surface");
}

/// `NN` extensions.
pub mod nn {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NN_vi_surface.html>
    pub const VI_SURFACE: ExtensionName = name(b"VK_NN_vi_surface");
}

/// `NV` extensions.
pub mod nv {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_clip_space_w_scaling.html>
    pub const CLIP_SPACE_W_SCALING: ExtensionName = name(b"VK_NV_clip_space_w_scaling");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_compute_shader_derivatives.html>
    pub const COMPUTE_SHADER_DERIVATIVES: ExtensionName = name(b"VK_NV_compute_shader_derivatives");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_cooperative_matrix.html>
    pub const COOPERATIVE_MATRIX: ExtensionName = name(b"VK_NV_cooperative_matrix");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_corner_sampled_image.html>
    pub const CORNER_SAMPLED_IMAGE: ExtensionName = name(b"VK_NV_corner_sampled_image");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_coverage_reduction_mode.html>
    pub const COVERAGE_REDUCTION_MODE: ExtensionName = name(b"VK_NV_coverage_reduction_mode");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_dedicated_allocation.html>
    #[deprecated(note = "deprecated in favor of `VK_KHR_dedicated_allocation`")]
    pub const DEDICATED_ALLOCATION: ExtensionName = name(b"VK_NV_dedicated_allocation");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_dedicated_allocation_image_aliasing.html>
    pub const DEDICATED_ALLOCATION_IMAGE_ALIASING: ExtensionName =
        name(b"VK_NV_dedicated_allocation_image_aliasing");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_device_diagnostics_config.html>
    pub const DEVICE_DIAGNOSTICS_CONFIG: ExtensionName = name(b"VK_NV_device_diagnostics_config");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_device_diagnostic_checkpoints.html>
    pub const DEVICE_DIAGNOSTIC_CHECKPOINTS: ExtensionName =
        name(b"VK_NV_device_diagnostic_checkpoints");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_device_generated_commands.html>
    pub const DEVICE_GENERATED_COMMANDS: ExtensionName = name(b"VK_NV_device_generated_commands");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_external_memory.html>
    #[deprecated(note = "deprecated in favor of `VK_KHR_external_memory`")]
    pub const EXTERNAL_MEMORY: ExtensionName = name(b"VK_NV_external_memory");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_external_memory_capabilities.html>
    #[deprecated(note = "deprecated in favor of `VK_KHR_external_memory_capabilities`")]
    pub const EXTERNAL_MEMORY_CAPABILITIES: ExtensionName =
        name(b"VK_NV_external_memory_capabilities");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_external_memory_win32.html>
    #[deprecated(note = "deprecated in favor of `VK_KHR_external_memory_win32`")]
    pub const EXTERNAL_MEMORY_WIN32: ExtensionName = name(b"VK_NV_external_memory_win32");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_fill_rectangle.html>
    pub const FILL_RECTANGLE: ExtensionName = name(b"VK_NV_fill_rectangle");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_fragment_coverage_to_color.html>
    pub const FRAGMENT_COVERAGE_TO_COLOR: ExtensionName = name(b"VK_NV_fragment_coverage_to_color");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_fragment_shader_barycentric.html>
    pub const FRAGMENT_SHADER_BARYCENTRIC: ExtensionName =
        name(b"VK_NV_fragment_shader_barycentric");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_framebuffer_mixed_samples.html>
    pub const FRAMEBUFFER_MIXED_SAMPLES: ExtensionName = name(b"VK_NV_framebuffer_mixed_samples");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_geometry_shader_passthrough.html>
    pub const GEOMETRY_SHADER_PASSTHROUGH: ExtensionName =
        name(b"VK_NV_geometry_shader_passthrough");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_glsl_shader.html>
    #[deprecated]
    pub const GLSL_SHADER: ExtensionName = name(b"VK_NV_glsl_shader");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_mesh_shader.html>
    pub const MESH_SHADER: ExtensionName = name(b"VK_NV_mesh_shader");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_ray_tracing.html>
    pub const RAY_TRACING: ExtensionName = name(b"VK_NV_ray_tracing");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_representative_fragment_test.html>
    pub const REPRESENTATIVE_FRAGMENT_TEST: ExtensionName =
        name(b"VK_NV_representative_fragment_test");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_sample_mask_override_coverage.html>
    pub const SAMPLE_MASK_OVERRIDE_COVERAGE: ExtensionName =
        name(b"VK_NV_sample_mask_override_coverage");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_scissor_exclusive.html>
    pub const SCISSOR_EXCLUSIVE: ExtensionName = name(b"VK_NV_scissor_exclusive");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_shader_image_footprint.html>
    pub const SHADER_IMAGE_FOOTPRINT: ExtensionName = name(b"VK_NV_shader_image_footprint");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_shader_sm_builtins.html>
    pub const SHADER_SM_BUILTINS: ExtensionName = name(b"VK_NV_shader_sm_builtins");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_shader_subgroup_partitioned.html>
    pub const SHADER_SUBGROUP_PARTITIONED: ExtensionName =
        name(b"VK_NV_shader_subgroup_partitioned");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_shading_rate_image.html>
    pub const SHADING_RATE_IMAGE: ExtensionName = name(b"VK_NV_shading_rate_image");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_viewport_array2.html>
    pub const VIEWPORT_ARRAY2: ExtensionName = name(b"VK_NV_viewport_array2");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_viewport_swizzle.html>
    pub const VIEWPORT_SWIZZLE: ExtensionName = name(b"VK_NV_viewport_swizzle");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NV_win32_keyed_mutex.html>
    pub const WIN32_KEYED_MUTEX: ExtensionName = name(b"VK_NV_win32_keyed_mutex");
}

/// `NVX` extensions.
pub mod nvx {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NVX_image_view_handle.html>
    pub const IMAGE_VIEW_HANDLE: ExtensionName = name(b"VK_NVX_image_view_handle");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_NVX_multiview_per_view_attributes.html>
    pub const MULTIVIEW_PER_VIEW_ATTRIBUTES: ExtensionName =
        name(b"VK_NVX_multiview_per_view_attributes");
}

/// `QCOM` extensions.
pub mod qcom {
    use super::*;

    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_QCOM_render_pass_shader_resolve.html>
    pub const RENDER_PASS_SHADER_RESOLVE: ExtensionName =
        name(b"VK_QCOM_render_pass_shader_resolve");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_QCOM_render_pass_store_ops.html>
    pub const RENDER_PASS_STORE_OPS: ExtensionName = name(b"VK_QCOM_render_pass_store_ops");
    /// <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_QCOM_render_pass_transform.html>
    pub const RENDER_PASS_TRANSFORM: ExtensionName = name(b"VK_QCOM_render_pass_transform");
}

#[inline]
const fn name(bytes: &[u8]) -> ExtensionName {
    let mut name = [0; MAX_EXTENSION_NAME_SIZE];

    let mut index = 0;
    while index < bytes.len() {
        name[index] = bytes[index] as c_char;
        index += 1;
    }

    if bytes.is_empty() || bytes[bytes.len() - 1] != 0 {
        name[bytes.len()] = 0;
    }

    name
}
